stages:
  - Build
  - Package

before_script:
  - export CI_COMMIT_SHA_SHORT=$(echo ${CI_COMMIT_SHA} | cut -c -8)

compile:
  image: golang:1.8.1
  stage: Build
  variables:
    CGO_ENABLED: '0'
  script:
    - ls -lah
    - ln -s /builds /go/src/github.com
    - cd /go/src/github.com/prometheus/pushgateway
    - make -j $(getconf _NPROCESSORS_ONLN) build
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 4 weeks

# end-to-end:
#   stage: Build
#   variables:
#     PROMETHEUS_DOCKER_REGISTRY: "${CI_REGISTRY_IMAGE}"
#     PROMETHEUS_DOCKER_IMAGE_TAG: "${CI_COMMIT_REF_SLUG}.job.${CI_JOB_ID}"
#   script:
#     - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
#     - docker build -t "$CI_REGISTRY_IMAGE/prometheus-e2e:$PROMETHEUS_DOCKER_IMAGE_TAG" ./e2e/
#     - docker push "$CI_REGISTRY_IMAGE/prometheus-e2e:$PROMETHEUS_DOCKER_IMAGE_TAG"

container:
  stage: Package
  image: docker:latest
  script:
    - IMAGE_TAG=${CI_COMMIT_REF_NAME}.${CI_COMMIT_SHA_SHORT}.${CI_JOB_ID}
    - cd /builds/prometheus/pushgateway
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - echo export IMAGE=$CI_REGISTRY_IMAGE | tee release.env
    - echo export TAG=$IMAGE_TAG | tee -a release.env
    - cat release.env
  dependencies:
    - compile
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 4 weeks
    paths:
      - release.env
